"""add whatsapp_messages table

Revision ID: 1a64775b9378
Revises: 318b4d2dd87f
Create Date: 2026-05-14 06:05:59.816390

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1a64775b9378"
down_revision: Union[str, None] = "318b4d2dd87f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "whatsapp_messages",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column("message_text", sa.Text(), nullable=False),
        sa.Column(
            "message_type",
            sa.Enum("INCOME", "EXPENSE", "QUERY", "OTHER", name="messagetype"),
            nullable=False,
        ),
        sa.Column("extracted_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("response_text", sa.Text(), nullable=True),
        sa.Column("transaction_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"], ["transactions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_whatsapp_messages_phone_number"),
        "whatsapp_messages",
        ["phone_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_whatsapp_messages_user_id"),
        "whatsapp_messages",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_whatsapp_messages_user_id"), table_name="whatsapp_messages")
    op.drop_index(
        op.f("ix_whatsapp_messages_phone_number"), table_name="whatsapp_messages"
    )
    op.drop_table("whatsapp_messages")
    # ### end Alembic commands ###
